// "use strict";
// Object.defineProperty(exports, "__esModule", { value: true });
// exports.states = exports.data = void 0;
// exports.data = [
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     },
//     {
//         oid: 'OID 101',
//         outletname: 'Rajput Store',
//         projectName: 'Media Player',
//         rId: 'RID - 12345',
//         projectType: 'Digital Screen',
//         region: 'East',
//         tme: 'DNEGI',
//         vendorName: 'Ajey Dhore',
//         lifecyclestage: 'Stock Transfer',
//         status: 'Ohio',
//         action: 'Edit',
//     }
// ];
// //50 us states array
// exports.states = [
//     'Alabama',
//     'Alaska',
//     'Arizona',
//     'Arkansas',
//     'California',
//     'Colorado',
//     'Connecticut',
//     'Delaware',
//     'Florida',
//     'Georgia',
//     'Hawaii',
//     'Idaho',
//     'Illinois',
//     'Indiana',
//     'Iowa',
//     'Kansas',
//     'Kentucky',
//     'Louisiana',
//     'Maine',
//     'Maryland',
//     'Massachusetts',
//     'Michigan',
//     'Minnesota',
//     'Mississippi',
//     'Missouri',
//     'Montana',
//     'Nebraska',
//     'Nevada',
//     'New Hampshire',
//     'New Jersey',
//     'New Mexico',
//     'New York',
//     'North Carolina',
//     'North Dakota',
//     'Ohio',
//     'Oklahoma',
//     'Oregon',
//     'Pennsylvania',
//     'Rhode Island',
//     'South Carolina',
//     'South Dakota',
//     'Tennessee',
//     'Texas',
//     'Utah',
//     'Vermont',
//     'Virginia',
//     'Washington',
//     'West Virginia',
//     'Wisconsin',
//     'Wyoming',
//     'Puerto Rico',
// ];








"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.states = exports.data = void 0;
exports.data = [
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
  {
    oid: "OID 101",
    outletname: "Rajput Store",
    projectName: "Media Player",
    rId: "RID - 12345",
    projectType: "Digital Screen",
    region: "East",
    tme: "DNEGI",
    vendorName: "Ajey Dhore",
    lifecyclestage: "Stock Transfer",
    status: "Ohio",
    action: "Edit",
  },
];
//50 us states array
exports.states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Puerto Rico",
];
