"use client"
import React from 'react';
import './global.css';


import { ParamsProvider } from './ParamContext';

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    lang: string;
    // other fields of params
  };
}

export const metadata = {
  title: 'Welcome to hive',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children, params }: RootLayoutProps) {
  console.log("params", params);

  if (!params) {
    return <div>Error: Params not provided!</div>; // or handle this case in another appropriate way
  }

  return (
    <ParamsProvider params={params}>
      <html lang={params.lang}>
      
        <body>{children}</body>
      </html>
    </ParamsProvider>
  );
}
